- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 3600
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Human
            - Harpy
            - Dwarf
        - !type:CharacterTraitRequirement
          traits:
            - Mk3LoyaltyImplant
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Shadowkin
        - IPC
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
    - !type:CharacterEmployerRequirement
      employers:
      - NanoTrasen
      - IdrisIncorporated
  weight: 10 # DeltaV - Changed HoP weight from 20 to 10 due to them not being more important than other Heads
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Hydroponics
  - External
  - Cryogenics
  - Lawyer
  - Cargo
  - Boxer
  - Clown
  - Library
  - Mime
  - Musician
  - Reporter
  - Zookeeper
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: HoPGear
  subGear:
  - HoPPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpack
    shoes: ClothingShoesLeather
    id: HoPPDA
    ears: ClothingHeadsetHoP
  storage:
    back:
    - Flash

- type: startingGear
  id: HoPPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitHoP
    head: ClothingHeadEnvirohelmHoP
    gloves: ClothingHandsGlovesEnviroglovesHoP
